### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by bonomat** [nostrdice/nostrdice#8]
What is left: 

```[tasklist]
### Tasks
- [ ] https://github.com/get10101/nostr-dice/issues/14
- [ ] https://github.com/get10101/nostr-dice/issues/15
- [ ] https://github.com/get10101/nostr-dice/issues/17
- [ ] https://github.com/get10101/nostr-dice/issues/13
- [ ] https://github.com/get10101/nostr-dice/issues/21
- [ ] https://github.com/get10101/nostr-dice/issues/22
- [ ] https://github.com/get10101/nostr-dice/issues/23
- [ ] https://github.com/get10101/nostr-dice/issues/16
- [x] Don't allow users to zap old notes
- [x] optional: expire multiplier notes (so that they will get deleted after the round)
- [x] optional: Check if pubkey (of zap request) has a lightning address, reject otherwise.
```

**Comment by bonomat** [comment]
All done besides: https://github.com/nostrdice/nostrdice/issues/17
